#!/bin/bash 

# Kubernetes namespace to use for application
NAMESPACE=cv
# MySQL config
MYSQL_DATABASE_NAME=${NAMESPACE}
MYSQL_USER_USERNAME='api'
# Istio config
ISTIO_PROFILE=demo
# Cert Manager config
CERT_MANAGER_VERSION=v0.14.2
# State (apply/delete)
STATE=${1:-apply} 

# Metallb config
kubectl $STATE -f ./spec/metal.yaml

# Istio installation
if [[ $STATE = "apply" ]]
then
istioctl manifest apply \
  --set profile=$ISTIO_PROFILE \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.global.k8sIngress.gatewayName=ingressgateway
elif [[ $STATE = "delete" ]]
then 
istioctl manifest generate \
  --set profile=$ISTIO_PROFILE \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.global.k8sIngress.gatewayName=ingressgateway | kubectl delete -f -
else
echo "unknown arg"
fi

# Enable istio sidecar auto injection for namespace
kubectl label namespace $NAMESPACE istio-injection=enabled --overwrite

# Read more at https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/
# Patch install to define tls ingress usage
kubectl -n istio-system \
      patch gateway istio-autogenerated-k8s-ingress --type=json \
        -p='[{"op": "replace", "path": "/spec/servers/1/tls", "value": {"credentialName": "ingress-cert", "mode": "SIMPLE", "privateKey": "sds", "serverCertificate": "sds"}}]'

# Install certmanager
kubectl $STATE -f https://github.com/jetstack/cert-manager/releases/download/$CERT_MANAGER_VERSION/cert-manager.yaml

# Certificate config
kubectl $STATE -f ./spec/certificates.yaml

# Namespace
kubectl $STATE -f ./spec/namespace.yaml

# Database secrets dynamic generation
cat <<EOF | kubectl $STATE -f -
apiVersion: v1
kind: Secret
metadata:
  name: mysql-config
  namespace: ${NAMESPACE}
type: Opaque
data:
  MYSQL_DATABASE_NAME: $(echo -n "${MYSQL_DATABASE_NAME}" | base64 -w0)
  MYSQL_ROOT_PASSWORD: $(echo -n "${MYSQL_ROOT_PASSWORD}" | base64 -w0)
  MYSQL_USER_USERNAME: $(echo -n "${MYSQL_USER_USERNAME}" | base64 -w0)
  MYSQL_USER_PASSWORD: $(echo -n "${MYSQL_USER_PASSWORD}" | base64 -w0)
EOF

# Database
kubectl $STATE -f ./spec/database.yaml

# Rest API
kubectl $STATE -f ./spec/api.yaml

# Cron Jobs
kubectl $STATE -f ./spec/cron.yaml

# Istio config
kubectl $STATE -f ./spec/istio.yaml
